In [1]:
import json
import pandas as pd
import pprint
import numpy as np

In [3]:
# Opening JSON file
f = open('/home/davidyue/Documents/filerepo/Research/multiagent-human-experiment/mturk/experiment_data/mturk-experiment-1.json',)
  
data = json.load(f)

f.close()

Data is a list of dictionaries, where each dictionary corresponds to one MTurk assignment.

In [4]:
pd.DataFrame.from_dict(data)

,HITId,AssignmentId,WorkerId,workerId,results
0,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,3OVR4I9USZSFXM4HAR977G8SSDM4QL,AYQRV4ORFKL4S,AYQRV4ORFKL4S,"{'data': [{}, {'age': '2534', 'gender': 'Man'}..."
1,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,3ZPBJO59KZAFKPO7KCN616AXE3JHDF,A104X3BZA5LAZ6,A104X3BZA5LAZ6,"{'data': [{}, {'age': '2534', 'gender': 'Man'}..."
2,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,3DR23U6WEFNAH4T2G1FFL7V6P9FETF,AOCKR0R2CEORY,AOCKR0R2CEORY,"{'data': [{}, {'age': '3544', 'gender': 'Man'}..."
3,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,33LK57MYL3E7DZ7JNOO2WC02BW9ZSG,A3K9GTQBOI7O5A,A3K9GTQBOI7O5A,"{'data': [{}, {'age': '2534', 'gender': 'Woman..."
4,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,3PMBY0YE2HCC0R0AM4434JURAQZC9K,A3G8OON0TDPN1E,A3G8OON0TDPN1E,"{'data': [{}, {'age': '3544', 'gender': 'Man'}..."
5,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,3HWRJOOETFB924GNR1APB2ZKNQ1ESQ,A268VYM822TUNU,A268VYM822TUNU,"{'data': [{}, {'age': '3544', 'gender': 'Man'}..."
6,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,3IRIK4HM3KTPI8YCOX1RK93PKPX6C9,A2I960JYUZ8KAV,A2I960JYUZ8KAV,"{'data': [{}, {'age': '2534', 'gender': 'Man'}..."
7,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,3ATTHHXXWKXTEQ48HU63VPE4UY9XIP,A30BA8X1BW7GGS,A30BA8X1BW7GGS,"{'data': [{}, {'age': '3544', 'gender': 'Man'}..."
8,3ICOHX7EOLK6EBZHSXM4DCXETSIE0E,39RP059MER28X6RYXDCDYLUTS4EBMJ,A2QACB3VV0PLAD,A2QACB3VV0PLAD,"{'data': [{}, {'age': '2534', 'gender': 'Woman..."

In [12]:
output = pd.DataFrame()

for assignment in data:
    output = output.append(assignment['results']['data'][-2], ignore_index=True)


feedback_1 = 'How good was your partner at playing the game?'
feedback_2 = 'Did you have any issues with the task or the interface?'
feedback_3 = 'Was the game too short, too long, or a good length?'

pd.set_option('display.max_colwidth', None)
output

,feedbackAdditional,feedbackBugs,feedbackLength
0,None,None,I was like this game .
1,GOOD,GOOD,GOOD
2,good,good,good
3,no,no,60 seconds. I would like the game to be longer.
4,cool beans,"none, all good",60 seconds was good
5,None,No,Good..
6,,,
7,good,good,good
8,no,yes its some network issues,shorter like so much